### PR TITLE
Implement virtualized rendering

### PR DESCRIPTION
**Pull request by eug-vs**

### CODE REVIEW

**Comment by eug-vs** [comment]
So here I've shown an implementation of _full-page component_, but it has some restrictions, and we don't have time to mess up with them for now. Specifically, it's **real pain** to make list items dynamically change their heights. But nevertheless, it fits our _current_ use-case and the performance is unbelievable - we have no limitations on list sizes now.
My idea is to turn this component into some sort of window or frame, which would then be embedded into other pages and server _only one narrow purpose_ - show the list of items.

**Comment by eug-vs** [comment]
Also, **most importantly**, this PR makes browser window unscrollable, or in other words - fixes it's size. What that means is that in future we will have to consider this when building layouts and adjust them to match this property.

**Comment by asketonim** [comment]
I've familiarized myself with the solution that _react-window_ provides and that's exactly what I was thinking about when we had those problems with slow rendering on the Scoreboard! Looking forward to work with it.

**Comment by asketonim** [comment]
> Also, **most importantly**, this PR makes browser window unscrollable, or in other words - fixes it's size. What that means is that in future we will have to consider this when building layouts and adjust them to match this property.

I think it affects only the page we use _react-window_ on. And that page will serve one purpose: showing a list of solutions.

**Comment by asketonim** [comment]
I might be wrong about your intentions of using this feature.

**Review by asketonim — APPROVED** [review]
Seems like a decent feature. Perfect for our app.

**Comment by eug-vs** [comment]
Will merge that as it is, since there's a massive upcoming change in a separate request, which is out of this one's scope.

**Pull request merged**
