### PR TITLE
Add icons to Header

### PR DESCRIPTION
**Pull request by eug-vs**
It might not look as clean as before, but I think icons are always good when it comes to building a good UI. @asketonim, what's your opinion?

### CODE REVIEW

**Comment by asketonim** [comment]
> It might not look as clean as before, but I think icons are always good when it comes to building a good UI. @asketonim, what's your opinion?

- Indeed, comparing two pages (with and without icons) I might say the one without icons looks cleaner.
image

- On another hand, it takes less time for user to navigate on the page.
From how it looks - _no icons_, from how it feels - _yes icons_.
I might have missed something, so I need a response from you.

**Comment by eug-vs** [comment]
@asketonim, yeah, this duality is a problem. Maybe we could polish our logo a bit, so it fits this bar better and then we can go with the icons?

**Comment by eug-vs** [comment]
@asketonim, also check out this variants: 
image
image

**Comment by asketonim** [comment]
I like the second one. I guess that's what we need.

**Comment by eug-vs** [comment]
@asketonim, I am still not sure :laughing: . Final choice:
image
image


P.S: I like the **last** one more

**Comment by asketonim** [comment]
Yeah, the last one.
We can easily change it at any time, so let's move on.

**Review by asketonim — APPROVED** [review]

**Pull request merged**
